---
# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json

options:
  # this option tells presenterm you don't care about extra parameters in
  # presentation's front matter. This can be useful if you're trying to load a
  # presentation made for another tool
  strict_front_matter_parsing: false
