[tools]
chezmoi = "latest"
adr-tools = "latest"
hurl = "latest"
granted = "latest"
pre-commit = "latest"
cf = "latest"
uv = "latest"
python = "3.13"
just = "latest"

[settings]
idiomatic_version_file_enable_tools = []
